### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [bachya/pyopenuv#39]
**Describe the bug**
Asynctest doesn't work with Python 3.8 and above.

Asynctest upstream is aware of this breakage and recommends using the built-in AsyncMock instead.

See also Martiusweb/asynctest#144 and Martiusweb/asynctest#126

**Comment by bachya** [comment]
Thanks for letting me know. In order to not break tests for 3.6/3.7, I'll have to look at importing this from `futures`.

**Comment by bachya** [comment]
Appreciate the heads up. How do I fix those so that I can still run 3.6/3.7 tests?
