### ISSUE TITLE
Retry in case of error 500

### ISSUE THREAD

**Issue by parautenbach** [bachya/pyopenuv#48]
**Is your feature request related to a problem? Please describe.**
This relates to issue [48120](https://github.com/home-assistant/core/issues/48120) of HA core where there are reports of the upstream returning an error 500 quite often. It would be nice if this client library (or perhaps the HA implementation) could implement some retry logic.

**Describe the solution you'd like**
Retry the request in case of an upstream error or timeout.

**Additional context**
I'm not sure whether requests returning an error response counts towards the daily quota.

**Comment by bachya** [comment]
GitHub Actions is having issues at the moment, but as soon as they're back, I'll publish a new version and get it into HA.
